version: "3"

services:
  hermes:
    build: .
    ports:
      - 9999:9999
      - 8000:8000
    environment:
      DATABASE_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
